var express = require('express');
var router = express.Router();

var http = require('http');

function GetPageService(name, observer) {
	this.name = name;
	this.observer = observer;
	this.http = http;
}

GetPageService.prototype.getPage = function(url) {
	var options = {
		host: url,
		path: '/'
	};
	this.http.get(options, this.onGetPageCallback());
};

GetPageService.prototype.onGetPageCallback = function() {
	observer = this.observer;
	name = this.name;
	console.log("get the callback for http.get method")
	return function(response) {
		console.log("running callback generated by GetPageService Object called "+name+" that will call the observer:" + observer.name);
	  	var str = '';
	  	response.on('data', function (chunk) {
	    	str += chunk;
		 });

		response.on('end', function () {
		    console.log(str);
		    observer.getPageSuccess(str)
		});
	};
};

function GetPageController(name, response) {
	this.name = name;
	this.response = response;
	this.getPageSuccess = function(page) {
		 this.response.send('Hello, obtained page: ' +  page);
	};
}

router.get('/', function(req, res, next) {
	var observer = new GetPageController("pedro", res);
	var service = new GetPageService("juan", observer);
	service.getPage("www.example.com");
});

module.exports = router;
